/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorkflowDefinition {
  workflowName: string;
  steps: StepDefinition[];
  definitions: DefinitionsSchema;
}
export interface StepDefinition {
  name: string;
  retries?: number;
  timeoutSeconds?: number;
  transitionToStep?: null | string;
  integrationDetails: IntegrationDetails;
}
export interface IntegrationDetails {
  type: string;
  inputTransformer?: InputTransformerSchema;
  inputDefinition: RefSchema;
  outputDefinition: RefSchema;
}
export interface InputTransformerSchema {
  fieldset: FieldsetSchema[];
}
export interface FieldsetSchema {
  from?: string;
  to?: string;
  valueToKey?: boolean;
  withValueFrom?: string;
  withTemplate?: string;
  toArray?: boolean;
  via?: {
    type: "date" | "commands";
    sourceFormat?: string;
    format?: string;
  };
  fromEach?: {
    field: string;
    to?: string;
    flatten?: boolean;
    fieldset?: FieldsetSchema[];
  };
}
export interface RefSchema {
  $ref: string;
}
export interface DefinitionsSchema {
  [k: string]: DefinitionSchema;
}
export interface DefinitionSchema {
  type: string;
  properties?: {
    [k: string]: DefinitionSchema;
  };
  items?: DefinitionSchema;
  required?: string[];
  additionalProperties?: boolean;
}
